### ISSUE TITLE
cannot find this package

### ISSUE THREAD

**Issue by Melonia-H** [Learning-and-Intelligent-Systems/mit-ros-pkg#1]
hello .i come form china and cannot get mit-ros-pkg from https://svn.csail.mit.edu/mit-ros-pkg . i am learnning hand detection ,can you help me , send me a package.

**Comment by arii** [comment]
@maohuui

We are working on finding this package. Unfortunately, it has not been updated past Fuerte.  Please stay tuned.

**Comment by arii** [comment]
I have updated the code from our svn repo.  It has not been updated since fuerte.
